import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

const CANONICAL_SCHEMA_PATH = resolve("prisma", "schema.prisma");
const GENERATED_SCHEMA_PATH = resolve("prisma", "schema.generated.prisma");

export function resolvePrismaProvider(
  databaseUrl = process.env.DATABASE_URL,
  explicitProvider = process.env.GREENPROOF_DB_PROVIDER
) {
  const normalizedExplicitProvider = explicitProvider?.trim().toLowerCase();

  if (normalizedExplicitProvider === "postgres" || normalizedExplicitProvider === "postgresql") {
    return "postgresql";
  }

  if (normalizedExplicitProvider === "sqlite") {
    return "sqlite";
  }

  const normalizedDatabaseUrl = databaseUrl?.trim().toLowerCase();

  if (!normalizedDatabaseUrl) {
    return "sqlite";
  }

  if (
    normalizedDatabaseUrl.startsWith("postgres://") ||
    normalizedDatabaseUrl.startsWith("postgresql://") ||
    normalizedDatabaseUrl.startsWith("prisma+postgres://")
  ) {
    return "postgresql";
  }

  return "sqlite";
}

export function resolveSqliteFilePath(databaseUrl = process.env.DATABASE_URL) {
  const rawUrl = databaseUrl?.trim();

  if (!rawUrl || !rawUrl.startsWith("file:")) {
    return resolve("prisma", "dev.db");
  }

  const rawPath = rawUrl.slice("file:".length);

  if (!rawPath || rawPath === "./dev.db") {
    return resolve("prisma", "dev.db");
  }

  if (/^[A-Za-z]:[\\/]/.test(rawPath) || rawPath.startsWith("/")) {
    return rawPath;
  }

  return resolve("prisma", rawPath.replace(/^\.\//, ""));
}

export function renderSchema() {
  const provider = resolvePrismaProvider();
  const canonicalSchema = readFileSync(CANONICAL_SCHEMA_PATH, "utf8");
  const providerPattern = /provider\s*=\s*"(?:sqlite|postgresql)"/;

  if (!providerPattern.test(canonicalSchema)) {
    throw new Error("Failed to render prisma/schema.generated.prisma because the datasource provider marker was not found.");
  }

  const renderedSchema = canonicalSchema.replace(
    providerPattern,
    `provider = "${provider}"`
  );

  const header = `// This file is auto-generated by prisma/render-schema.mjs.\n// Edit prisma/schema.prisma instead.\n\n`;
  writeFileSync(GENERATED_SCHEMA_PATH, `${header}${renderedSchema}`);

  return {
    provider,
    generatedSchemaPath: GENERATED_SCHEMA_PATH
  };
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { provider, generatedSchemaPath } = renderSchema();
  console.info(`Rendered Prisma schema for provider "${provider}" at ${generatedSchemaPath}.`);
}
